# Generated by Django 4.0.5 on 2022-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photorepo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photorepo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
