# Generated by Django 4.0.5 on 2022-07-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_alter_photorepo_created_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoRepo',
            new_name='PhotoAlbum',
        ),
    ]
